version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "browser",
    "jquery"
  ]
  style_guide = "standard"

[[transformers]]
name = "standardjs"
enabled = true